name: smtp
version: 1.0.0
description: An SMTP 5321 server implementation in Dart.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/smtp
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  async: ">=1.0.0 <3.0.0"
  dart2_constant: ^1.0.0
  http_parser: ^3.0.0
  intl: ^0.15.0
dev_dependencies:
  mailer: ^1.0.0
  test: