name: smtp
version: 2.0.0
description: An SMTP 5321 server implementation in the Dart language.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/smtp
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  async: ^2.0.0
  buffer: ^1.0.0
  collection: ^1.0.0
  http_parser: ^3.0.0
  mime: ^0.9.0
dev_dependencies:
  mailer: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0